version: 0.1
log:
  fields:
    service: registry
    environment: development
storage:
    delete:
      enabled: true
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    debug:
        addr: localhost:5001
    headers:
        X-Content-Type-Options: [nosniff]
redis:
  addr: localhost:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
metadata:
  enabled : true
  type : "inmemory"
